flowchart BT
    %% =========================
    %% DM
    %% =========================
    subgraph DM["DM"]
        direction LR
        DC["dim_customers"]
        DP["dim_products"]
        DPR["dim_promotions"]
        DD["dim_deliveries"]
        DSE["dim_stores / dim_employees_scd"]
        DDT["dim_dates"]
        FF["fct_transactions_dd_dd"]
    end

    %% =========================
    %% DWH
    %% =========================
    subgraph DWH["DWH"]
        direction LR

        MC["stg.mapping_customers"]
        MP["stg.mapping_products"]
        MT["stg.mapping_transactions"]

        NFR["nf reference\nnf_states\nnf_cities\nnf_addresses\nnf_product_categories\nnf_promotion_types\nnf_shipping_partners"]

        NFM["nf master entities\nnf_customers\nnf_products\nnf_promotions\nnf_deliveries\nnf_engagements\nnf_stores"]

        NFE["nf_employees_scd"]
        NFT["nf_transactions"]
    end

    %% =========================
    %% LANDING
    %% =========================
    subgraph LAND["Landing"]
        direction LR
        SLON["sl_online_retail\n- frg_online_retail\n- src_online_retail_raw\n- src_online_retail"]

        SLOFF["sl_offline_retail\n- frg_offline_retail\n- src_offline_retail_raw\n- src_offline_retail"]
    end

    %% =========================
    %% SOURCE
    %% =========================
    subgraph SRC["Source"]
        direction LR

        subgraph OS["Online Source System"]
            O1["online CSV - customers"]
            O2["online CSV - products"]
            O3["online CSV - sales"]
        end

        subgraph FS["Offline Source System"]
            F1["offline CSV - customers"]
            F2["offline CSV - stores"]
            F3["offline CSV - employees"]
            F4["offline CSV - sales"]
        end
    end

    %% =========================
    %% FLOWS
    %% =========================
    O1 --> SLON
    O2 --> SLON
    O3 --> SLON

    F1 --> SLOFF
    F2 --> SLOFF
    F3 --> SLOFF
    F4 --> SLOFF

    SLON --> MC
    SLON --> MP
    SLON --> MT

    SLOFF --> MT
    SLOFF --> NFM
    SLOFF --> NFE

    MC --> NFM
    MP --> NFR
    MP --> NFM
    MT --> NFT

    NFR --> NFM
    NFM --> FF
    NFE --> DSE
    NFT --> FF

    NFM --> DC
    NFM --> DP
    NFM --> DPR
    NFM --> DD
    NFM --> DSE

    DDT --> FF
    DC --> FF
    DP --> FF
    DPR --> FF
    DD --> FF
    DSE --> FF
