-- for first bulk load DROP is okay. But later, it can not be acceptable.
DROP FOREIGN TABLE IF EXISTS sl_offline_retail.frg_offline_retail;
DROP FOREIGN TABLE IF EXISTS sl_online_retail.frg_online_retail;

CREATE FOREIGN TABLE sl_offline_retail.frg_offline_retail (
  customer_id              VARCHAR(1000),
  gender                   VARCHAR(1000),
  marital_status           VARCHAR(1000),
  transaction_id           VARCHAR(1000),
  transaction_date         VARCHAR(1000),
  product_id               VARCHAR(1000),
  product_category         VARCHAR(1000),
  quantity                 VARCHAR(1000),
  unit_price               VARCHAR(1000),
  discount_applied         VARCHAR(1000),
  day_of_week              VARCHAR(1000),
  week_of_year             VARCHAR(1000),
  month_of_year            VARCHAR(1000),
  product_name             VARCHAR(1000),
  product_brand            VARCHAR(1000),
  product_stock            VARCHAR(1000),
  product_material         VARCHAR(1000),
  promotion_id             VARCHAR(1000),
  promotion_type           VARCHAR(1000),
  promotion_start_date     VARCHAR(1000),
  promotion_end_date       VARCHAR(1000),
  customer_zip_code        VARCHAR(1000),
  customer_city            VARCHAR(1000),
  customer_state           VARCHAR(1000),
  store_zip_code           VARCHAR(1000),
  store_city               VARCHAR(1000),
  store_state              VARCHAR(1000),
  date_of_birth            VARCHAR(1000),
  payment_method           VARCHAR(1000),
  delivery_id              VARCHAR(1000),
  delivery_type            VARCHAR(1000),
  delivery_status          VARCHAR(1000),
  shipping_partner         VARCHAR(1000),
  employee_salary          VARCHAR(1000),
  membership_date          VARCHAR(1000),
  store_location           VARCHAR(1000),
  last_purchase_date       VARCHAR(1000),
  total_sales              VARCHAR(1000),
  product_manufacture_date VARCHAR(1000),
  product_expiry_date      VARCHAR(1000),
  promotion_channel        VARCHAR(1000),
  employee_name            VARCHAR(1000),
  employee_position        VARCHAR(1000),
  employee_hire_date       VARCHAR(1000)
)
SERVER csv_server
OPTIONS (
  filename  '/content/data/01_empty_95_off.csv', 
  format    'csv',
  header    'true',
  delimiter ',',
  quote     '"',
  escape    '"'
);

CREATE FOREIGN TABLE sl_online_retail.frg_online_retail (
  customer_id              VARCHAR(1000),
  gender                   VARCHAR(1000),
  marital_status           VARCHAR(1000),
  transaction_id           VARCHAR(1000),
  transaction_date         VARCHAR(1000),
  product_id               VARCHAR(1000),
  product_category         VARCHAR(1000),
  quantity                 VARCHAR(1000),
  unit_price               VARCHAR(1000),
  discount_applied         VARCHAR(1000),
  day_of_week              VARCHAR(1000),
  week_of_year             VARCHAR(1000),
  month_of_year            VARCHAR(1000),
  product_name             VARCHAR(1000),
  product_brand            VARCHAR(1000),
  product_stock            VARCHAR(1000),
  product_material         VARCHAR(1000),
  promotion_id             VARCHAR(1000),
  promotion_type           VARCHAR(1000),
  promotion_start_date     VARCHAR(1000),
  promotion_end_date       VARCHAR(1000),
  customer_zip_code        VARCHAR(1000),
  customer_city            VARCHAR(1000),
  customer_state           VARCHAR(1000),
  customer_support_calls   VARCHAR(1000),
  date_of_birth            VARCHAR(1000),
  payment_method           VARCHAR(1000),
  delivery_id              VARCHAR(1000),
  delivery_type            VARCHAR(1000),
  delivery_status          VARCHAR(1000),
  shipping_partner         VARCHAR(1000),
  membership_date          VARCHAR(1000),
  website_address          VARCHAR(1000),
  order_channel            VARCHAR(1000),
  customer_support_method  VARCHAR(1000),
  issue_status             VARCHAR(1000),
  product_manufacture_date VARCHAR(1000),
  product_expiry_date      VARCHAR(1000),
  total_sales              VARCHAR(1000),
  promotion_channel        VARCHAR(1000),
  last_purchase_date       VARCHAR(1000),
  app_usage                VARCHAR(1000),
  website_visits           VARCHAR(1000),
  social_media_engagement  VARCHAR(1000),
  engagement_id            VARCHAR(1000)
)
SERVER csv_server
OPTIONS (
  filename  '/content/data/02_empty_95_on.csv',
  format    'csv',
  header    'true',
  delimiter ',',
  quote     '"',
  escape    '"'
);

