
   -- 1) FOREIGN TABLE FILE POINTERS -> 95% if its needed but for the first bulk load, no needed.

--ALTER FOREIGN TABLE sl_offline_retail.frg_offline_retail
  --OPTIONS (SET filename '/content/data/01_empty_95_off.csv');

--ALTER FOREIGN TABLE sl_online_retail.frg_online_retail
  --OPTIONS (SET filename '/content/data/02_empty_95_on.csv');

 -- 2) RAW TABLES CLEAN START FOR BULK DEMO
DROP TABLE IF EXISTS sl_offline_retail.src_offline_retail_raw;
CREATE TABLE sl_offline_retail.src_offline_retail_raw (
  customer_id              VARCHAR(1000),
  gender                   VARCHAR(1000),
  marital_status           VARCHAR(1000),
  transaction_id           VARCHAR(1000),
  transaction_date         VARCHAR(1000),
  product_id               VARCHAR(1000),
  product_category         VARCHAR(1000),
  quantity                 VARCHAR(1000),
  unit_price               VARCHAR(1000),
  discount_applied         VARCHAR(1000),
  day_of_week              VARCHAR(1000),
  week_of_year             VARCHAR(1000),
  month_of_year            VARCHAR(1000),
  product_name             VARCHAR(1000),
  product_brand            VARCHAR(1000),
  product_stock            VARCHAR(1000),
  product_material         VARCHAR(1000),
  promotion_id             VARCHAR(1000),
  promotion_type           VARCHAR(1000),
  promotion_start_date     VARCHAR(1000),
  promotion_end_date       VARCHAR(1000),
  customer_zip_code        VARCHAR(1000),
  customer_city            VARCHAR(1000),
  customer_state           VARCHAR(1000),
  store_zip_code           VARCHAR(1000),
  store_city               VARCHAR(1000),
  store_state              VARCHAR(1000),
  date_of_birth            VARCHAR(1000),
  payment_method           VARCHAR(1000),
  delivery_id              VARCHAR(1000),
  delivery_type            VARCHAR(1000),
  delivery_status          VARCHAR(1000),
  shipping_partner         VARCHAR(1000),
  employee_salary          VARCHAR(1000),
  membership_date          VARCHAR(1000),
  store_location           VARCHAR(1000),
  last_purchase_date       VARCHAR(1000),
  total_sales              VARCHAR(1000),
  product_manufacture_date VARCHAR(1000),
  product_expiry_date      VARCHAR(1000),
  promotion_channel        VARCHAR(1000),
  employee_name            VARCHAR(1000),
  employee_position        VARCHAR(1000),
  employee_hire_date       VARCHAR(1000),
  insert_dt                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  batch_id                 BIGINT,
  load_type                VARCHAR(20),
  source_file_name         VARCHAR(255),
  load_dts                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  source_row_num           BIGINT
  );

DROP TABLE IF EXISTS sl_online_retail.src_online_retail_raw;
CREATE TABLE sl_online_retail.src_online_retail_raw (
  customer_id              VARCHAR(1000),
  gender                   VARCHAR(1000),
  marital_status           VARCHAR(1000),
  transaction_id           VARCHAR(1000),
  transaction_date         VARCHAR(1000),
  product_id               VARCHAR(1000),
  product_category         VARCHAR(1000),
  quantity                 VARCHAR(1000),
  unit_price               VARCHAR(1000),
  discount_applied         VARCHAR(1000),
  day_of_week              VARCHAR(1000),
  week_of_year             VARCHAR(1000),
  month_of_year            VARCHAR(1000),
  product_name             VARCHAR(1000),
  product_brand            VARCHAR(1000),
  product_stock            VARCHAR(1000),
  product_material         VARCHAR(1000),
  promotion_id             VARCHAR(1000),
  promotion_type           VARCHAR(1000),
  promotion_start_date     VARCHAR(1000),
  promotion_end_date       VARCHAR(1000),
  customer_zip_code        VARCHAR(1000),
  customer_city            VARCHAR(1000),
  customer_state           VARCHAR(1000),
  customer_support_calls   VARCHAR(1000),
  date_of_birth            VARCHAR(1000),
  payment_method           VARCHAR(1000),
  delivery_id              VARCHAR(1000),
  delivery_type            VARCHAR(1000),
  delivery_status          VARCHAR(1000),
  shipping_partner         VARCHAR(1000),
  membership_date          VARCHAR(1000),
  website_address          VARCHAR(1000),
  order_channel            VARCHAR(1000),
  customer_support_method  VARCHAR(1000),
  issue_status             VARCHAR(1000),
  product_manufacture_date VARCHAR(1000),
  product_expiry_date      VARCHAR(1000),
  total_sales              VARCHAR(1000),
  promotion_channel        VARCHAR(1000),
  last_purchase_date       VARCHAR(1000),
  app_usage                VARCHAR(1000),
  website_visits           VARCHAR(1000),
  social_media_engagement  VARCHAR(1000),
  engagement_id            VARCHAR(1000),
  insert_dt                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  batch_id                 BIGINT,
  load_type                VARCHAR(20),
  source_file_name         VARCHAR(255),
  load_dts                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  source_row_num           BIGINT
  );


